### ISSUE TITLE
My understanding of promises

### ISSUE THREAD

**Issue by TehShrike** [sindresorhus/p-immediate#1]
I thought the Promises spec mandated that all functions passed to `.then` should be called in a new stack already - what am I missing?

**Comment by sindresorhus** [comment]
Promises are resolved in a microtask, the current event loop, this delays it to a new event loop.

Good read about this: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by TehShrike** [comment]
Thanks!
