### ISSUE TITLE
Multiple ticks / microtasks

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [sindresorhus/p-immediate#5]
It would be helpful if we could just use `pImmediate(3)`, which would resolve after 3 microtasks.

**Comment by sindresorhus** [comment]
What's the use-case for this? I cannot think of any reasonable code doing this.

**Comment by ChocolateLoverRaj** [comment]
Now that I think about it I no longer have any use-cases. I used to use a similar function which resolved after 2 microtasks, but I no longer do, so this feature is unnecessary.
